### ISSUE TITLE
about stability

### ISSUE THREAD

**Issue by xmglin** [xiedacon/lua-resty-logger#1]
Is it stable, and will log lines be cross-line mal-disposited, when high concurrency of HTTP traffic?
I will apply your logger to production. any suggestion?

**Comment by xiedacon** [comment]
> Is it stable

Yes

> will log lines be cross-line mal-disposited, when high concurrency of HTTP traffic?

The logs where be flushed with a timer, which means the max concurrent is the number of nginx worker thread

> any suggestion

In highly concurrency
  * Output as less log as you can, only error and necessary info 
  * Use ``table.concat`` to serial string
